name: liquify
description: >
  A powerful and extensible Liquid template engine for Dart.
  Supports full Liquid syntax, custom tags and filters, and high-performance parsing and rendering.

version: 1.5.1

repository: https://github.com/kingwill101/liquify

topics:
  - liquid
  - templating
  - teamplate-engine
  - dart

resolution: workspace
environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  petitparser: ^7.0.0
  html: ^0.15.6
  html_unescape: ^2.0.0
  intl: ^0.20.2
  timezone: ^0.11.0
  gato: ^0.0.5+1
  file: ^7.0.1
  args: ^2.7.0
  logging: ^1.3.0

dev_dependencies:
  lints: ^6.0.0
  meta: ^1.17.0
  stack_trace: ^1.12.1
  test: ^1.29.0
  coverage: ^1.15.0

funding:
  - https://www.buymeacoffee.com/kingwill101
